In [1]:
from benchmark_data import *
from Req import * 
from GraphTheory.benchmarking_christofides import christofides1
from ant_colony import ant_colony
from SA import sa
from time import time
from numpy.random import shuffle
trials = 1

In [ ]:
for mat in mat_list[:1]:
    times = []
    results = []
    map = gen_ran(len(mat))
    map.D = mat
    for i in range(trials):
        t0 = time()
        result = brute_tour(map).cost()
        t1 = time()
        times.append(t1-t0)
        results.append(result)
    print(sum(times)/trials, results)

In [6]:
for mat in mat_list[:1]:
    times = []
    results = []
    map = gen_ran(len(mat))
    map.D = mat
    for i in range(trials):
        t0 = time()
        result = held_karp(map).cost()
        t1 = time()
        times.append(t1-t0)
        results.append(result)
    print(sum(times)/trials, results)


0.4196500778198242 [1733]


In [7]:
for mat in mat_list:
    times = []
    results = []
    map = gen_ran(len(mat))
    map.D = mat
    for i in range(trials):
        t0 = time()
        result = nearest_neighbour(map).cost()
        t1 = time()
        times.append(t1-t0)
        results.append(result)
    print(sum(times)/trials, results)

6.461143493652344e-05 [2110]
0.00025272369384765625 [36388.05923226534]
0.0005168914794921875 [9748.94670516838]
0.014028072357177734 [709.5216278258143]
0.03471112251281738 [11892.888058614652]
0.10831904411315918 [3148.109934934404]
0.2628912925720215 [2071.8621488390363]
1.32173752784729 [3244.8069297875477]
1.9007289409637451 [102594.35793052983]
3.901592969894409 [117733.69616508145]


In [10]:
for mat in mat_list:
    times = []
    results = []
    map = gen_ran(len(mat))
    map.D = mat
    for i in range(trials):
        t0 = time()
        result = best_nn(map).cost()
        t1 = time()
        times.append(t1-t0)
        results.append(result)
    print(sum(times)/trials, results)

0.0011055469512939453 [1733]
0.007414579391479492 [32161.40297490449]
0.02046680450439453 [6770.07692171576]
1.6979701519012451 [628.7206044979843]
7.116898059844971 [11330.393196425215]


In [3]:
trials = 1
for mat in mat_list:
    times = []
    map = gen_ran(len(mat))
    map.D = mat
    for i in range(trials):
        t0 = time()
        result = christofides1(mat, True)
        t1 = time()
        times.append(t1-t0)
    print(sum(times)/trials, sum(result))



0.04363608360290527 2145
0.06386661529541016 31827.811555692748
0.06623077392578125 6758.586205818501
0.45848894119262695 612.1855197792014
1.3885328769683838 10314.249774868978
2.130051851272583 2916.0846625271392
3.4170966148376465 1824.7342412062023
29.85619854927063 2813.7313098897266
59.728346824645996 86748.90475170662
110.29957175254822 105264.39875520446


In [14]:
for mat in mat_list:
    times = []
    results = []
    map = gen_ran(len(mat))
    map.D = mat
    tour = nearest_neighbour(map)
    for i in range(trials):
        t0 = time()
        result = repeated_2_opt(tour).cost()
        t1 = time()
        times.append(t1-t0)
        results.append(result)
    print(sum(times)/trials, results)

0.0019986629486083984 [1948]
0.010716676712036133 [33967.634851134164]
0.03509378433227539 [9128.995705703926]
0.798304557800293 [676.2229381020024]
2.469017505645752 [11674.318734230075]
14.456514596939087 [3117.195425903057]
37.1878867149353 [2018.1968018301347]
209.49356818199158 [3196.368879427386]
308.26665902137756 [100733.740754702]
647.9748277664185 [115409.98841118564]


In [2]:
for mat in mat_list:
    times = []
    results = []
    n = len(mat) 
    map = gen_ran(n)
    map.D = mat
    for i in range(trials):
        t0 = time()
        result = ant_colony(map, its_max=n).cost()
        t1 = time()
        times.append(t1-t0)
        results.append(result)
    print(sum(times)/trials, results)

/home/spull/M2R/M2R/ant_colony/ant_colony.py:35: RuntimeWarning: divide by zero encountered in true_divide
  eta = 1/map.D
0.08156895637512207 [1733]
0.47640204429626465 [30071.601193364484]
1.0073235034942627 [6803.943881718994]
31.89253282546997 [637.4563065256128]
85.69383955001831 [11140.753316454455]
/home/spull/M2R/M2R/ant_colony/ant_colony.py:60: RuntimeWarning: invalid value encountered in true_divide
  prob_roulette = prob_roulette/sum(prob_roulette)
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
[[0.         0.05       0.04152274 ... 0.02311251 0.02906191 0.0559017 ]
 [0.05       0.         0.05423261 ... 0.02760788 0.03571429 0.1118034 ]
 [0.04152274 0.05423261 0.         ... 0.05076731 0.09284767 0.1       ]
 ...
 [0.02311251 0.02760788 0.05076731 ... 0.         0.1118034  0.03434014]
 [0.02906191 0.03571429 0.09284767 ... 0.1118034  0.         0.04902903]
 [0.055901

ValueError: 

In [ ]:
for mat in mat_list:
    times = []
    results = []
    n = len(mat) 
    map = gen_ran(n)
    map.D = mat
    tour = Hamiltonian(shuffle(),)
    for i in range(trials):
        t0 = time()
        result = ant_colony(map, m=((3*n)//2))
        t1 = time()
        times.append(t1-t0)
        results.append(result)
    print(sum(times)/trials, results)